IT4Change/IT4C.dev

docs/people/ulf-gebhardt.md

jobs in Norway

---

docs/people/ulf-gebhardt.md

Some typos in a profile are fixed

fix(profile): fix some typos in profile

---

.github/workflows/lint_pr.yml

feat(workflow): lint-pr workflow

---

docs/index.md

Remove double bracket on index page.
- None

feat(content): remove double bracket on index page

---

docs/people/wolfgang-huss.md

fix(content): wolle profile fixes

---

.github/workflows/vuepress-deploy.yml

fix the deployment still using a deleted script
- None

fix(other): fix deploy

---

.github/workflows/test-build.yml
.github/workflows/test-lint.yml

This tries to fix forks not running required workflows.
- relates #60

fix(workflow): run workflows when pullrequest is targeting this repo

---

.github/workflows/test-build.yml
.github/workflows/test-lint.yml
.github/workflows/vuepress-deploy.yml

Fixes a syntax error in the deploy workflow.
Also removes duplicate checks due to `pull_request_target` and `push`
- None

fix(workflow): fix deploy workflow

---

.github/workflows/lint_pr.yml
.github/workflows/test-build.yml
.github/workflows/test-lint.yml
README.md

lint readme & test target for workflows
- None

fix(workflow): lint readme & test target for workflows

---

.github/dependabot.yml

feat(other): add dependabot for Github Actions and packages

---

.github/workflows/vuepress-deploy.yml

remove cname to have proper deployment on github.
This might be the solution for https://it4change.github.io/IT4C.dev/ to work properly.
- None

fix(workflow): remove cname

---

.github/workflows/lint_pr.yml

exclude dependabot from pr title validation
- None

fix(workflow): exclude dependabot from pr title validation

---

.github/workflows/vuepress-deploy.yml

Include cname to fix gh-pages deployment.
⚠️  Untested and untestable.
This is the page currently deployed to https://it4change.github.io/IT4C.dev/

fix(workflow): include cname to fix gh-pages deploy

---

docs/contact.md

Publish new email address on contact page
- None

feat(content): new email-address

---

docs/.vuepress/config.js
docs/index.md

remove people and projects not maintained yet
- None

fix(content): remove people and projects not maintained yet

---

docs/history.md

Remove an unappropriate section from the history page
- None

refactor(content): remove unnecessary text from history page

---

docs/.vuepress/config.js
package-lock.json
package.json

vuepress - correctly use bundle option now required
Details: https://vuepress.github.io/reference/bundler/vite.html
- None

chore(other): vuepress - correctly use bundle option now required

---

README.md
docs/projects/gradido.md

fix(content): md remarks

---

docs/.vuepress/config/theme.js
docs/index.md
docs/projects/democracy.app.md
docs/projects/gradido.md
docs/projects/ocelot.social.md

feat(content): describe democracy app

---

docs/.vuepress/config/theme.js
docs/index.md
docs/projects/dreammall.md

feat(content): describe dreammall

---

.github/dependabot.yml

Reverts IT4Change/IT4C.dev#157

chore(other): set dependabot package update pr limit to 99

---

package-lock.json
package.json

chore(other): update packages 2024 04 14

---

.github/workflows/vuepress-deploy.yml
README.md

refactor(other): use our vuepress deploy action in workflows

---

.github/dependabot.yml

To facilitate package update maintenance, related packages are now grouped in the Dependabot Bump PRs.
This makes it possible to reduce the number of bump PRs in a sensible and comprehensible way and avoids failing PRs due to mutual dependencies.
- None

refactor(other): dependabot group updates

---

docs/index.md
docs/projekte/democracy.app.md

refactor(other): some translation fixes

---

docs/.vuepress/config/theme.js

refactor(other): add max to side menu

---

docs/team/ulf-gebhardt.md

content: update Ulf Gebhardt
- Adds new Datapoints for Projects
- Adds new Datapoint for Travels
- Remvoes a sentence in the introduction
- Fixes the tables
- None

refactor(content): update Ulf Gebhardt

---

docs/.vuepress/config.js
package-lock.json
package.json

command dev prod
adds a new command `npm run dev-prod` which build the project and then
spins up a http server. This was implemented to be able to test certain
scenarious like image compression.
- based on #259

feat(other): command dev-prod

---

README.md

Docs:  describe the requirements to get `vuepress-plugin-imagemin` compiling on alpine
For `vuepress-plugin-imagemin` there are several system packages required to properly compile it. It is now documented in the README.md.
Switch from `bash` to `sh` highlighting.
- None

docs(other): describe the requirements to get `vuepress-plugin-imagemin` compiling on alpine

---

backend/package-lock.json

security update for backend packages
- None

fix(other): security update for backend packages

---

docs/.vuepress/styles/config.scss

[Change the default theme color](https://theme-hope.vuejs.press/guide/interface/theme-color.html#setting-default-theme-color) from Hope's green to the bluish color of the footer.

refactor(other): set default theme color to footer color

---

docs/index.md

refactor(content): fix reference issue

---

docs/index.md

fix dreammall description
remove superfluous comma
- None

fix(content): dreammall description

---

docs/.vuepress/components/ContactForm.vue
docs/.vuepress/styles/index.scss

The missing margins betweens the formular inputs were caused by a tailwind bug around space-y-4. I just switched to "my-4"
- None

fix(content): contact form

---

package-lock.json
package.json

fix(workflow): add sass-embedded, re-add platform-specific dependencies

---

docs/.vuepress/layouts/BlankLayout.vue
docs/projekte/dreammall.md
docs/projekte/ocelot.social.md

vuepress style fixes
Old
New
- None

fix(other): vuepress style fixes

---

docs/.vuepress/components/ContactForm.vue

Changes wording in contact form text. "Sie" => "Du"

fix(content): change wording to more informal approach ("sie" => "du")

---

docs/impressum.md
docs/team/ulf-gebhardt.md

In the imprint and Ulf's profile some formal approaches where left.

fix(content): fix informal approach in imprint and ulf profile

---

docs/.vuepress/components/ContactForm.vue

Reduce image size besides contact form and changes its position. It's also sticky now.
- fixes #290

fix(content): smaller contact form image

---

.github/workflows/automerge.yml

fix(workflow): use different token

---

.github/workflows/automerge.yml

automerge dependabot token
- None

fix(workflow): automerge dependabot token

---

package-lock.json
package.json

fix tailwind version definition
- None

fix(other): fix tailwind version definition

---

backend/package.json

some types are required for tsc to work
- None

fix(other): types for production

---

backend/package.json

fix(backend): fix start command

---

.github/dependabot.yml

dependabot for backend and docker
- None

feat(workflow): dependabot for backend and docker

---

README.md

fix image path in README.md
- None

fix(content): fix image path in README.md
